SparkplugB feature addition to agent
Open-IoT-Service-Platform/oisp-iot-agent pull request #40
Opened 2022-05-05 12:31 UTC by yshashix

SparkplugB functionality added with how to enable in README file

2022-05-06 12:08 UTC, srware requested changes

2022-05-06 13:36 UTC, srware commented on config/config.json.template
> +            "rejectUnauthorized": false
Can we re-use the 'secure' or 'strictSSL' config options which already exist for MQTT?

2022-05-06 17:19 UTC, yshashix commented on config/config.json.template
> +            "rejectUnauthorized": false
Yes, I checked and it's the same at the end.

2022-05-06 18:18 UTC, yshashix commented on config/config.json.template
> +            "swVersion": "v1.0.0",
Currently, i don't see commands to set attributes of the device at agent, in data/device.json though there is api for it.
So for now I set default value for this parameter and will update code once it is added in device.json or any other file.

2022-05-19 20:53 UTC, scooter1556 requested changes

2022-05-19 20:53 UTC, scooter1556 commented on lib/cloud.proxy.js
> +            me.spbMetricList= [];
```suggestion
            me.spbMetricList = [];
```

2022-05-19 20:53 UTC, scooter1556 commented on lib/cloud.proxy.js
> +                        var compMetric= {
```suggestion
                        var compMetric = {
```

2022-05-19 20:53 UTC, scooter1556 commented on lib/cloud.proxy.js
> +            me.devProf ={
```suggestion
            me.devProf = {
```

2022-05-19 20:53 UTC, scooter1556 commented on lib/cloud.proxy.js
> +            me.logger.info("SparkplugB Mqtt proxy found! Configuring  Sparkplug and MQTT for data sending.");
```suggestion
            me.logger.info("SparkplugB MQTT proxy found! Configuring Sparkplug and MQTT for data sending.");
```

2022-05-19 20:53 UTC, scooter1556 commented on lib/cloud.proxy.js
> +            if (deviceConf.device_token && me.spBProxy!= undefined) {
```suggestion
            if (deviceConf.device_token && me.spBProxy != undefined) {         
```

2022-05-19 20:53 UTC, scooter1556 commented on lib/cloud.proxy.js
> +                    if(err === "fail") {
```suggestion
                    if (err === "fail") {
```

2022-05-19 20:53 UTC, scooter1556 commented on lib/cloud.proxy.js
> +                    }else{
```suggestion
                    } else {
```

2022-05-19 20:53 UTC, scooter1556 commented on lib/cloud.proxy.js
> +                        me.logger.info("SparkplugB MQTT NBIRTH Metric sent succesfully for eonid: %j ",me.gatewayId );
```suggestion
                        me.logger.info("SparkplugB MQTT NBIRTH Metric sent succesfully for eonid: %j ", me.gatewayId);
```

2022-05-19 20:53 UTC, scooter1556 commented on lib/cloud.proxy.js
> +                    if(err === "fail") {
```suggestion
                    if (err === "fail") {
```

2022-05-19 20:53 UTC, scooter1556 commented on lib/cloud.proxy.js
> +                    }else{
```suggestion
                    } else {
```

2022-05-19 20:53 UTC, scooter1556 commented on lib/cloud.proxy.js
> +                        me.logger.error("SparkplugB MQTT DBIRTH Metric not send, probably connection error ");
```suggestion
                        me.logger.error("SparkplugB MQTT DBIRTH Metric not sent!");
```

2022-05-19 20:53 UTC, scooter1556 commented on lib/cloud.proxy.js
> +                        me.logger.info("SparkplugB MQTT DBIRTH Metric sent succesfully for device: %j ",me.deviceId);
```suggestion
                        me.logger.info("SparkplugB MQTT DBIRTH Metric sent succesfully for device: %j ", me.deviceId);
```

2022-05-19 20:53 UTC, scooter1556 commented on lib/cloud.proxy.js
> +        }else{
```suggestion
        } else {
```

2022-05-19 20:53 UTC, scooter1556 commented on lib/cloud.proxy.js
> +
```suggestion

```

2022-05-19 20:53 UTC, scooter1556 commented on lib/cloud.proxy.js
> +                    if(compMetric != undefined) {
```suggestion
                    if (compMetric != undefined) {
```

2022-05-19 20:53 UTC, scooter1556 commented on lib/cloud.proxy.js
> +            }else{
```suggestion
            } else { 
```

2022-05-19 20:53 UTC, scooter1556 commented on lib/cloud.proxy.js
> +                if(compMetric != undefined) {
```suggestion
                if (compMetric != undefined) {
```

2022-05-19 20:53 UTC, scooter1556 commented on lib/cloud.proxy.js
> +                }else {
```suggestion
                } else {
```

2022-05-19 20:53 UTC, scooter1556 commented on lib/cloud.proxy.js
> +                    if(err === "fail") {
```suggestion
                    if (err === "fail") { 
```

2022-05-19 20:53 UTC, scooter1556 commented on lib/cloud.proxy.js
> +                    }else{
```suggestion
                        me.logger.error("SparkplugB MQTT DDATA Metric not sent!");
                    } else {
```

2022-05-19 20:53 UTC, scooter1556 commented on lib/cloud.proxy.js
> +                    callback(err)
```suggestion
                        me.logger.info("SparkplugB MQTT DDATA Metric sent successfully with payload %j", componentMetrics);
                    }     
                    callback(err);
```

2022-05-19 20:53 UTC, scooter1556 commented on lib/cloud.proxy.js
> +                        callback(null, response)
```suggestion
                        callback(null, response);
```

2022-05-19 20:53 UTC, scooter1556 commented on lib/cloud.proxy.js
> +        }else if (me.mqttProxy != undefined) {
```suggestion
        } else if (me.mqttProxy != undefined) {
```

2022-05-19 20:53 UTC, scooter1556 commented on lib/cloud.proxy.js
> +            });
```suggestion
            }); 
```

2022-05-19 20:53 UTC, scooter1556 commented on lib/data.submission.js
> +            if(config.connector.mqtt.sparkplugB) {
```suggestion
            if (config.connector.mqtt.sparkplugB) {             
```

2022-05-19 20:53 UTC, scooter1556 commented on lib/data.submission.js
> +            }else {
```suggestion
            } else {
```

2022-05-19 20:53 UTC, scooter1556 commented on test/lib_data.submissionTests.js
>      };
```suggestion
    var store = {};
```

2022-05-19 20:53 UTC, scooter1556 commented on test/lib_data.submissionTests.js
> +    var conf ={
```suggestion
    var conf = {
```

2022-05-19 20:53 UTC, scooter1556 commented on test/lib_cloudproxyTest.js
> +    var conf ={
```suggestion
    var conf = {
```

2022-09-13 08:55 UTC, srware requested changes

2022-09-13 08:55 UTC, srware commented on README.md
> +For this you need to make certain changed on the config.json file as below in mqtt connector section (added in config.json.template):
```suggestion
1. To enable SparkplugB standard data format, you need to update the agent config as below:
```

2022-09-13 08:55 UTC, srware commented on lib/cloud.proxy.js
> +    */
Indentation is incorrect for comment.

2022-09-13 11:01 UTC, yshashix commented on README.md
> +For this you need to make certain changed on the config.json file as below in mqtt connector section (added in config.json.template):
I agree with this comment

2022-09-13 11:09 UTC, yshashix commented on README.md
> +
yes can be ommited with explicitly stating in heading that it needs SparkplugB enabled

2022-09-13 12:38 UTC, yshashix commented on lib/cloud.proxy.js
> +    */
changed

2022-09-15 10:18 UTC, scooter1556 approved these changes

2022-09-15 10:19 UTC, srware approved these changes

2022-09-15 10:19 UTC, merged